apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
type: Opaque
